# Travis CI Configuration File
# https://app.travis-ci.com/github/arcwindab/

language: php
os: linux
dist: xenial

php:
  - '5.6.33'
  - '5.6.40'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'
  
services:
  - 'mysql'
  
addons:
  mariadb: '5.5.52'
  
before_install:
  
  
before_script:
  - composer self-update
  - composer install

script: 
  - php test/index.php
  
  
matrix:
  allow_failures:
    
